version: '2'

services:

  paintedravendesign:
      image: 192.168.1.151:32000/paintedravendesign:1.0.2
      build:
          context: ./
          dockerfile: ./Dockerfile
      restart: unless-stopped
      ports:
          - "5001:443"
